### PR TITLE
Bug 533213 - rdf:Seq deserialization in JMH contains no elements

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533213

**Comment by berezovskyi** [comment]
https://git.eclipse.org/r/#/c/122364/

**Comment by berezovskyi** [comment]
https://git.eclipse.org/r/#/c/122364/

**Comment by berezovskyi** [comment]
@neormx could you please check the email you used to sign off? Was it supposed to be Gmail or Koneksys? The CLA email should match the one here.

**Comment by berezovskyi** [comment]
@neormx a reminder to fix the CLA/email warning

**Comment by berezovskyi** [comment]
@jamsden FYI, this are the Eclipse CLA checks in action ;)

**Comment by neormx** [comment]
The mail that matches the Eclipse CLA is the Gmail one, I mean neormx@gmail.com

**Comment by berezovskyi** [comment]
see #14

**Pull request closed without merging**
