### PR TITLE
Bug 518808 - make AllowedValues.getValues accept non-collection values

### PR DESCRIPTION
**Pull request by berezovskyi**
Contributed by Nick Crossley (ECA)

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=518808

**Comment by berezovskyi** [comment]
https://git.eclipse.org/r/#/c/100103/

**Comment by berezovskyi** [comment]
image

**Comment by ndjc** [comment]
I do not know the history of this design, or why it works the way it does/did.

**Pull request merged**
