### PR TITLE
Remove any logic from isWriteable

### LINKED ISSUE #21: isWriteable() check prevents from return an array of *different* RDF resources
`org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider#isWriteable` has the logic that checks the underlying type of the array for the OSLC annotations on the base class:

```
		if (type.getAnnotation(OslcResourceShape.class) != null ||
			type.getAnnotation(OslcNotQueryResult.class) != null)
		{
			// We do not have annotations when running from the non-web client.
			if (isCompatible(actualMediaType, requiredMediaTypes))
			{
				return true;
			}
		}
```

This is bad for 2 reasons:

1. It behaves differently under an OSLC Server (adaptor) and a standalone OSLC Client.
1. Its "smartness" will only work when, for example, a `Requirement[]` is returned where a method returns `Object[]`.

In my case, I hit the second problem because I was truly returning an `Object[]` with an instance of one valid OSLC resource class instance in `[0]` and another (different) valid OSLC resource class instance in `[1]`.

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #21

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden please review

**Comment by berezovskyi** [comment]
Alternatively, we can switch to a new provider as shown in #76 and leave this without changes but I can't imagine how this change would cause any backwards-incompatible changes.

**Comment by jamsden** [comment]
I am unable to review, clicking Add you review never completes.

**Comment by berezovskyi** [comment]
You can post it here if you wish.

**Pull request merged**
