### PR TITLE
Extract isWritable/isReadable checks from the abstract provider

### LINKED ISSUE #96: Removing all logic from AbstractOslcRdfXmlProvider::isWritable causes wrong JAX-RS Provider to handle arrays
The commit 
https://github.com/eclipse/lyo.core/commit/adad0119449af8d5c5c9b737fe02930b2310b5e8 removes all logic from isWritable. 

But one should not  return true, when the "type" parameter is an array!
 
When the response is a query response  (array), simply returning true, leads to the wrong OslcRdfXmlProvider Provider being called, instead of the expected OslcRdfXmlArrayProvider.
 
This causes JenaModelHelper to fail since it is not implemented to handle such a scenario.
Where it currently fails is in JenaModelHelper::recursivelyCollectNamespaceMappings, since the resourceClass parameter is an array instead of being a single object. This leads to the call "resourceClass.getPackage()" to return null, and hence cause an exception.

If we want isWritable  to be true in this abstract class, then we need to change the logic in the OslcRdfXmlProvider::isWritable method to make sure it returns false upon an array parameter.
What about all other classes that specialize this abstract class?

### PR DESCRIPTION
**Pull request by berezovskyi**
* added a single resource check to the Object provider; fixes #96
* no longer needed to list all names in the copyright header
  (https://bugs.eclipse.org/bugs/show_bug.cgi?id=435933)

### CODE REVIEW

**Comment by jadelkhoury** [comment]
Testing with a query service that is meant to return List<Requirement>, I get this exception:
java.lang.NullPointerException
	at org.eclipse.lyo.oslc4j.provider.jena.ProviderHelper.hasNotQueryResultTypeAnnot(ProviderHelper.java:20)
	at org.eclipse.lyo.oslc4j.provider.jena.ProviderHelper.isQueryResult(ProviderHelper.java:36)
	at org.eclipse.lyo.oslc4j.provider.jena.OslcRdfXmlCollectionProvider.writeTo(OslcRdfXmlCollectionProvider.java:108)
	at org.eclipse.lyo.oslc4j.provider.jena.OslcRdfXmlCollectionProvider.writeTo(OslcRdfXmlCollectionProvider.java:54)

**Comment by berezovskyi** [comment]
Thanks Jad, as you have predicted, that NPE was just waiting to hit us in the face. Will fix.

**Comment by jadelkhoury** [comment]
Simple tests I'm planning to run to test this patch. Please add necessary ones:
I will use https://github.com/OSLC/lyo-adaptor-sample-modelling, rm-adaptor.

- [ ] GET on a Requirement, using (1) rdf-xml (2) turtle
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by berezovskyi** [comment]
Another bug found:

image

May be related to https://github.com/eclipse/lyo.designer/pull/91

**Comment by jadelkhoury** [comment]
I can't see the bug. Can you please explain.
Also note that jsp pages are not regenerated, unless you delete the file. Whole content is generated within a single user-protected block.

**Comment by berezovskyi** [comment]
Apologies for a false alarm.

Unable to run the following test

> QUERY on a all Requirements from the testing-adaptor to make sure a client can unmarshel them, using (1) rdf-xml (2) turtle

due to https://github.com/OSLC/lyo-adaptor-sample-modelling/issues/35

**Comment by berezovskyi** [comment]
Confirmed the problem with the List return type:

image

**Comment by jadelkhoury** [comment]
I will fix OSLC/lyo-adaptor-sample-modelling#35 and run the tests. Thanks

**Pull request merged**
