### PR TITLE
Replace WebApplicationException w/ IllegalStateException

### LINKED ISSUE #92: OSLC Providers incorrectly raise 500 error
In `org/eclipse/lyo/oslc4j/provider/jena/AbstractOslcRdfXmlProvider.java:167`, we do something really strange: we catch _all_ exceptions and rethrow them as a `WebApplicationException`. Apparently, this was done to trigger a 500 error on the server side (which is wrong, because it's not Lyo's job to decide what code will the OSLC Server return when dealing with unexpected error). Worse still, when I hit this exception through Lyo Client, it fails similarly, making me think that the server returned 500 in _response_, while in fact Lyo Client did not even send a request yet.

Suggestion: rethrow an `IllegalStateException`

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #92

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@jamsden Andrei's argument sound reasonable to me. But good with a second opinion.

**Comment by jamsden** [comment]
How many API breaking cases will this change introduce?

**Comment by berezovskyi** [comment]
Only if you were trying to catch that exception (and were careful enough not to catch simply an Exception). This kind of defies the purpose of having an exception that triggers a 500 error when propagated to the framework and catch it at the same time. Neither IllegalStateException nor the WebApplicationException are checked exceptions, so there will be no compilation errors.

**Comment by jamsden** [comment]
Reviews still aren't working for me.
+1
Any exception that appears in an API method is part of the method's signature. Any change in a public API methods signature requires compilation changes in client code and may require additional exception handlers. So we should be thoughtful about how we change exceptions.

**Pull request merged**
